/*
 * Copyright 2001-2009, Haiku.
 * Distributed under the terms of the MIT License.
 *
 * Authors:
 *		Pahtz <pahtz@yahoo.com.au>
 *		Axel Dörfler, axeld@pinc-software.de
 */


/*!	Class for low-overhead port-based messaging */


#include <ServerLink.h>

#include <stdlib.h>
#include <string.h>
#include <new>

#include <AppDefs.h>
#include <ServerProtocol.h>


namespace BPrivate {


ServerLink::ServerLink()
{
}


ServerLink::~ServerLink()
{
}


void
ServerLink::SetTo(port_id sender, port_id receiver)
{
	fSender->SetPort(sender);
	fReceiver->SetPort(receiver);
}


status_t
ServerLink::FlushWithReply(int32& code)
{
	status_t status = Flush(B_INFINITE_TIMEOUT, true);
	if (status < B_OK)
		return status;

	return GetNextMessage(code);
}


const char*
ServerLink::GetMessageName(int32 code)
{
	switch (code) {
		case AS_GET_DESKTOP: return "AS_GET_DESKTOP";
		case AS_REGISTER_INPUT_SERVER: return "AS_REGISTER_INPUT_SERVER";
		case AS_EVENT_STREAM_CLOSED: return "AS_EVENT_STREAM_CLOSED";
		case AS_GET_WINDOW_LIST: return "AS_GET_WINDOW_LIST";
		case AS_GET_WINDOW_INFO: return "AS_GET_WINDOW_INFO";
		case AS_MINIMIZE_TEAM: return "AS_MINIMIZE_TEAM";
		case AS_BRING_TEAM_TO_FRONT: return "AS_BRING_TEAM_TO_FRONT";
		case AS_WINDOW_ACTION: return "AS_WINDOW_ACTION";
		case AS_GET_APPLICATION_ORDER: return "AS_GET_APPLICATION_ORDER";
		case AS_GET_WINDOW_ORDER: return "AS_GET_WINDOW_ORDER";
		case AS_CREATE_APP: return "AS_CREATE_APP";
		case AS_DELETE_APP: return "AS_DELETE_APP";
		case AS_QUIT_APP: return "AS_QUIT_APP";
		case AS_ACTIVATE_APP: return "AS_ACTIVATE_APP";
		case AS_APP_CRASHED: return "AS_APP_CRASHED";
		case AS_CREATE_WINDOW: return "AS_CREATE_WINDOW";
		case AS_CREATE_OFFSCREEN_WINDOW: return "AS_CREATE_OFFSCREEN_WINDOW";
		case AS_DELETE_WINDOW: return "AS_DELETE_WINDOW";
		case AS_CREATE_BITMAP: return "AS_CREATE_BITMAP";
		case AS_DELETE_BITMAP: return "AS_DELETE_BITMAP";
		case AS_GET_BITMAP_OVERLAY_RESTRICTIONS: return "AS_GET_BITMAP_OVERLAY_RESTRICTIONS";
		case AS_GET_BITMAP_SUPPORT_FLAGS: return "AS_GET_BITMAP_SUPPORT_FLAGS";
		case AS_RECONNECT_BITMAP: return "AS_RECONNECT_BITMAP";
		case AS_SET_CURSOR: return "AS_SET_CURSOR";
		case AS_SET_VIEW_CURSOR: return "AS_SET_VIEW_CURSOR";
		case AS_SHOW_CURSOR: return "AS_SHOW_CURSOR";
		case AS_HIDE_CURSOR: return "AS_HIDE_CURSOR";
		case AS_OBSCURE_CURSOR: return "AS_OBSCURE_CURSOR";
		case AS_QUERY_CURSOR_HIDDEN: return "AS_QUERY_CURSOR_HIDDEN";
		case AS_CREATE_CURSOR: return "AS_CREATE_CURSOR";
		case AS_CREATE_CURSOR_BITMAP: return "AS_CREATE_CURSOR_BITMAP";
		case AS_CLONE_CURSOR: return "AS_CLONE_CURSOR";
		case AS_DELETE_CURSOR: return "AS_DELETE_CURSOR";
		case AS_BEGIN_RECT_TRACKING: return "AS_BEGIN_RECT_TRACKING";
		case AS_END_RECT_TRACKING: return "AS_END_RECT_TRACKING";
		case AS_GET_CURSOR_POSITION: return "AS_GET_CURSOR_POSITION";
		case AS_GET_CURSOR_BITMAP: return "AS_GET_CURSOR_BITMAP";
		case AS_SHOW_OR_HIDE_WINDOW: return "AS_SHOW_OR_HIDE_WINDOW";
		case AS_INTERNAL_HIDE_WINDOW: return "AS_INTERNAL_HIDE_WINDOW";
		case AS_MINIMIZE_WINDOW: return "AS_MINIMIZE_WINDOW";
		case AS_QUIT_WINDOW: return "AS_QUIT_WINDOW";
		case AS_SEND_BEHIND: return "AS_SEND_BEHIND";
		case AS_SET_LOOK: return "AS_SET_LOOK";
		case AS_SET_FEEL: return "AS_SET_FEEL";
		case AS_SET_FLAGS: return "AS_SET_FLAGS";
		case AS_DISABLE_UPDATES: return "AS_DISABLE_UPDATES";
		case AS_ENABLE_UPDATES: return "AS_ENABLE_UPDATES";
		case AS_BEGIN_UPDATE: return "AS_BEGIN_UPDATE";
		case AS_END_UPDATE: return "AS_END_UPDATE";
		case AS_NEEDS_UPDATE: return "AS_NEEDS_UPDATE";
		case AS_SET_WINDOW_TITLE: return "AS_SET_WINDOW_TITLE";
		case AS_ADD_TO_SUBSET: return "AS_ADD_TO_SUBSET";
		case AS_REMOVE_FROM_SUBSET: return "AS_REMOVE_FROM_SUBSET";
		case AS_SET_ALIGNMENT: return "AS_SET_ALIGNMENT";
		case AS_GET_ALIGNMENT: return "AS_GET_ALIGNMENT";
		case AS_GET_WORKSPACES: return "AS_GET_WORKSPACES";
		case AS_SET_WORKSPACES: return "AS_SET_WORKSPACES";
		case AS_WINDOW_RESIZE: return "AS_WINDOW_RESIZE";
		case AS_WINDOW_MOVE: return "AS_WINDOW_MOVE";
		case AS_SET_SIZE_LIMITS: return "AS_SET_SIZE_LIMITS";
		case AS_ACTIVATE_WINDOW: return "AS_ACTIVATE_WINDOW";
		case AS_IS_FRONT_WINDOW: return "AS_IS_FRONT_WINDOW";
		case AS_CREATE_PICTURE: return "AS_CREATE_PICTURE";
		case AS_DELETE_PICTURE: return "AS_DELETE_PICTURE";
		case AS_CLONE_PICTURE: return "AS_CLONE_PICTURE";
		case AS_DOWNLOAD_PICTURE: return "AS_DOWNLOAD_PICTURE";
		case AS_SET_SYSTEM_FONT: return "AS_SET_SYSTEM_FONT";
		case AS_GET_SYSTEM_FONTS: return "AS_GET_SYSTEM_FONTS";
		case AS_GET_SYSTEM_DEFAULT_FONT: return "AS_GET_SYSTEM_DEFAULT_FONT";
		case AS_SYSTEM_FONT_CHANGED: return "AS_SYSTEM_FONT_CHANGED";
		case AS_GET_FONT_LIST_REVISION: return "AS_GET_FONT_LIST_REVISION";
		case AS_GET_FAMILY_AND_STYLES: return "AS_GET_FAMILY_AND_STYLES";
		case AS_GET_FAMILY_AND_STYLE: return "AS_GET_FAMILY_AND_STYLE";
		case AS_GET_FAMILY_AND_STYLE_IDS: return "AS_GET_FAMILY_AND_STYLE_IDS";
		case AS_GET_FONT_BOUNDING_BOX: return "AS_GET_FONT_BOUNDING_BOX";
		case AS_GET_TUNED_COUNT: return "AS_GET_TUNED_COUNT";
		case AS_GET_TUNED_INFO: return "AS_GET_TUNED_INFO";
		case AS_GET_FONT_HEIGHT: return "AS_GET_FONT_HEIGHT";
		case AS_GET_FONT_FILE_FORMAT: return "AS_GET_FONT_FILE_FORMAT";
		case AS_GET_EXTRA_FONT_FLAGS: return "AS_GET_EXTRA_FONT_FLAGS";
		case AS_GET_STRING_WIDTHS: return "AS_GET_STRING_WIDTHS";
		case AS_GET_EDGES: return "AS_GET_EDGES";
		case AS_GET_ESCAPEMENTS: return "AS_GET_ESCAPEMENTS";
		case AS_GET_ESCAPEMENTS_AS_FLOATS: return "AS_GET_ESCAPEMENTS_AS_FLOATS";
		case AS_GET_BOUNDINGBOXES_CHARS: return "AS_GET_BOUNDINGBOXES_CHARS";
		case AS_GET_BOUNDINGBOXES_STRING: return "AS_GET_BOUNDINGBOXES_STRING";
		case AS_GET_BOUNDINGBOXES_STRINGS: return "AS_GET_BOUNDINGBOXES_STRINGS";
		case AS_GET_HAS_GLYPHS: return "AS_GET_HAS_GLYPHS";
		case AS_GET_GLYPH_SHAPES: return "AS_GET_GLYPH_SHAPES";
		case AS_GET_UNICODE_BLOCKS: return "AS_GET_UNICODE_BLOCKS";
		case AS_GET_HAS_UNICODE_BLOCK: return "AS_GET_HAS_UNICODE_BLOCK";
		case AS_ADD_FONT_FILE: return "AS_ADD_FONT_FILE";
		case AS_ADD_FONT_MEMORY: return "AS_ADD_FONT_MEMORY";
		case AS_REMOVE_FONT: return "AS_REMOVE_FONT";
		case AS_VALID_SCREEN_ID: return "AS_VALID_SCREEN_ID";
		case AS_GET_NEXT_SCREEN_ID: return "AS_GET_NEXT_SCREEN_ID";
		case AS_SCREEN_GET_MODE: return "AS_SCREEN_GET_MODE";
		case AS_SCREEN_SET_MODE: return "AS_SCREEN_SET_MODE";
		case AS_PROPOSE_MODE: return "AS_PROPOSE_MODE";
		case AS_GET_MODE_LIST: return "AS_GET_MODE_LIST";
		case AS_GET_SCREEN_FRAME: return "AS_GET_SCREEN_FRAME";
		case AS_GET_PIXEL_CLOCK_LIMITS: return "AS_GET_PIXEL_CLOCK_LIMITS";
		case AS_GET_TIMING_CONSTRAINTS: return "AS_GET_TIMING_CONSTRAINTS";
		case AS_GET_DESKTOP_COLOR: return "AS_GET_DESKTOP_COLOR";
		case AS_SET_DESKTOP_COLOR: return "AS_SET_DESKTOP_COLOR";
		case AS_GET_SCREEN_ID_FROM_WINDOW: return "AS_GET_SCREEN_ID_FROM_WINDOW";
		case AS_READ_BITMAP: return "AS_READ_BITMAP";
		case AS_GET_RETRACE_SEMAPHORE: return "AS_GET_RETRACE_SEMAPHORE";
		case AS_GET_ACCELERANT_INFO: return "AS_GET_ACCELERANT_INFO";
		case AS_GET_MONITOR_INFO: return "AS_GET_MONITOR_INFO";
		case AS_SET_DPMS: return "AS_SET_DPMS";
		case AS_GET_DPMS_STATE: return "AS_GET_DPMS_STATE";
		case AS_GET_DPMS_CAPABILITIES: return "AS_GET_DPMS_CAPABILITIES";
		case AS_SCREEN_SET_BRIGHTNESS: return "AS_SCREEN_SET_BRIGHTNESS";
		case AS_SCREEN_GET_BRIGHTNESS: return "AS_SCREEN_GET_BRIGHTNESS";
		case AS_GET_ACCELERANT_PATH: return "AS_GET_ACCELERANT_PATH";
		case AS_GET_DRIVER_PATH: return "AS_GET_DRIVER_PATH";
		case AS_SET_UI_COLORS: return "AS_SET_UI_COLORS";
		case AS_SET_UI_COLOR: return "AS_SET_UI_COLOR";
		case AS_SET_DECORATOR: return "AS_SET_DECORATOR";
		case AS_GET_DECORATOR: return "AS_GET_DECORATOR";
		case AS_SET_CONTROL_LOOK: return "AS_SET_CONTROL_LOOK";
		case AS_GET_CONTROL_LOOK: return "AS_GET_CONTROL_LOOK";
		case AS_CURRENT_WORKSPACE: return "AS_CURRENT_WORKSPACE";
		case AS_ACTIVATE_WORKSPACE: return "AS_ACTIVATE_WORKSPACE";
		case AS_SET_WORKSPACE_LAYOUT: return "AS_SET_WORKSPACE_LAYOUT";
		case AS_GET_WORKSPACE_LAYOUT: return "AS_GET_WORKSPACE_LAYOUT";
		case AS_GET_SCROLLBAR_INFO: return "AS_GET_SCROLLBAR_INFO";
		case AS_SET_SCROLLBAR_INFO: return "AS_SET_SCROLLBAR_INFO";
		case AS_GET_MENU_INFO: return "AS_GET_MENU_INFO";
		case AS_SET_MENU_INFO: return "AS_SET_MENU_INFO";
		case AS_IDLE_TIME: return "AS_IDLE_TIME";
		case AS_SET_MOUSE_MODE: return "AS_SET_MOUSE_MODE";
		case AS_GET_MOUSE_MODE: return "AS_GET_MOUSE_MODE";
		case AS_SET_FOCUS_FOLLOWS_MOUSE_MODE: return "AS_SET_FOCUS_FOLLOWS_MOUSE_MODE";
		case AS_GET_FOCUS_FOLLOWS_MOUSE_MODE: return "AS_GET_FOCUS_FOLLOWS_MOUSE_MODE";
		case AS_SET_ACCEPT_FIRST_CLICK: return "AS_SET_ACCEPT_FIRST_CLICK";
		case AS_GET_ACCEPT_FIRST_CLICK: return "AS_GET_ACCEPT_FIRST_CLICK";
		case AS_GET_MOUSE: return "AS_GET_MOUSE";
		case AS_SET_DECORATOR_SETTINGS: return "AS_SET_DECORATOR_SETTINGS";
		case AS_GET_DECORATOR_SETTINGS: return "AS_GET_DECORATOR_SETTINGS";
		case AS_GET_SHOW_ALL_DRAGGERS: return "AS_GET_SHOW_ALL_DRAGGERS";
		case AS_SET_SHOW_ALL_DRAGGERS: return "AS_SET_SHOW_ALL_DRAGGERS";
		case AS_SET_SUBPIXEL_ANTIALIASING: return "AS_SET_SUBPIXEL_ANTIALIASING";
		case AS_GET_SUBPIXEL_ANTIALIASING: return "AS_GET_SUBPIXEL_ANTIALIASING";
		case AS_SET_HINTING: return "AS_SET_HINTING";
		case AS_GET_HINTING: return "AS_GET_HINTING";
		case AS_SET_SUBPIXEL_AVERAGE_WEIGHT: return "AS_SET_SUBPIXEL_AVERAGE_WEIGHT";
		case AS_GET_SUBPIXEL_AVERAGE_WEIGHT: return "AS_GET_SUBPIXEL_AVERAGE_WEIGHT";
		case AS_SET_SUBPIXEL_ORDERING: return "AS_SET_SUBPIXEL_ORDERING";
		case AS_GET_SUBPIXEL_ORDERING: return "AS_GET_SUBPIXEL_ORDERING";
		case AS_STROKE_ARC: return "AS_STROKE_ARC";
		case AS_STROKE_BEZIER: return "AS_STROKE_BEZIER";
		case AS_STROKE_ELLIPSE: return "AS_STROKE_ELLIPSE";
		case AS_STROKE_LINE: return "AS_STROKE_LINE";
		case AS_STROKE_LINEARRAY: return "AS_STROKE_LINEARRAY";
		case AS_STROKE_POLYGON: return "AS_STROKE_POLYGON";
		case AS_STROKE_RECT: return "AS_STROKE_RECT";
		case AS_STROKE_ROUNDRECT: return "AS_STROKE_ROUNDRECT";
		case AS_STROKE_SHAPE: return "AS_STROKE_SHAPE";
		case AS_STROKE_TRIANGLE: return "AS_STROKE_TRIANGLE";
		case AS_FILL_ARC: return "AS_FILL_ARC";
		case AS_FILL_ARC_GRADIENT: return "AS_FILL_ARC_GRADIENT";
		case AS_FILL_BEZIER: return "AS_FILL_BEZIER";
		case AS_FILL_BEZIER_GRADIENT: return "AS_FILL_BEZIER_GRADIENT";
		case AS_FILL_ELLIPSE: return "AS_FILL_ELLIPSE";
		case AS_FILL_ELLIPSE_GRADIENT: return "AS_FILL_ELLIPSE_GRADIENT";
		case AS_FILL_POLYGON: return "AS_FILL_POLYGON";
		case AS_FILL_POLYGON_GRADIENT: return "AS_FILL_POLYGON_GRADIENT";
		case AS_FILL_RECT: return "AS_FILL_RECT";
		case AS_FILL_RECT_GRADIENT: return "AS_FILL_RECT_GRADIENT";
		case AS_FILL_REGION: return "AS_FILL_REGION";
		case AS_FILL_REGION_GRADIENT: return "AS_FILL_REGION_GRADIENT";
		case AS_FILL_ROUNDRECT: return "AS_FILL_ROUNDRECT";
		case AS_FILL_ROUNDRECT_GRADIENT: return "AS_FILL_ROUNDRECT_GRADIENT";
		case AS_FILL_SHAPE: return "AS_FILL_SHAPE";
		case AS_FILL_SHAPE_GRADIENT: return "AS_FILL_SHAPE_GRADIENT";
		case AS_FILL_TRIANGLE: return "AS_FILL_TRIANGLE";
		case AS_FILL_TRIANGLE_GRADIENT: return "AS_FILL_TRIANGLE_GRADIENT";
		case AS_DRAW_STRING: return "AS_DRAW_STRING";
		case AS_DRAW_STRING_WITH_DELTA: return "AS_DRAW_STRING_WITH_DELTA";
		case AS_DRAW_STRING_WITH_OFFSETS: return "AS_DRAW_STRING_WITH_OFFSETS";
		case AS_SYNC: return "AS_SYNC";
		case AS_VIEW_CREATE: return "AS_VIEW_CREATE";
		case AS_VIEW_DELETE: return "AS_VIEW_DELETE";
		case AS_VIEW_CREATE_ROOT: return "AS_VIEW_CREATE_ROOT";
		case AS_VIEW_SHOW: return "AS_VIEW_SHOW";
		case AS_VIEW_HIDE: return "AS_VIEW_HIDE";
		case AS_VIEW_GET_COORD: return "AS_VIEW_GET_COORD";
		case AS_VIEW_SET_FLAGS: return "AS_VIEW_SET_FLAGS";
		case AS_VIEW_SET_ORIGIN: return "AS_VIEW_SET_ORIGIN";
		case AS_VIEW_GET_ORIGIN: return "AS_VIEW_GET_ORIGIN";
		case AS_VIEW_RESIZE_MODE: return "AS_VIEW_RESIZE_MODE";
		case AS_VIEW_BEGIN_RECT_TRACK: return "AS_VIEW_BEGIN_RECT_TRACK";
		case AS_VIEW_END_RECT_TRACK: return "AS_VIEW_END_RECT_TRACK";
		case AS_VIEW_DRAG_RECT: return "AS_VIEW_DRAG_RECT";
		case AS_VIEW_DRAG_IMAGE: return "AS_VIEW_DRAG_IMAGE";
		case AS_VIEW_SCROLL: return "AS_VIEW_SCROLL";
		case AS_VIEW_SET_LINE_MODE: return "AS_VIEW_SET_LINE_MODE";
		case AS_VIEW_GET_LINE_MODE: return "AS_VIEW_GET_LINE_MODE";
		case AS_VIEW_PUSH_STATE: return "AS_VIEW_PUSH_STATE";
		case AS_VIEW_POP_STATE: return "AS_VIEW_POP_STATE";
		case AS_VIEW_SET_SCALE: return "AS_VIEW_SET_SCALE";
		case AS_VIEW_GET_SCALE: return "AS_VIEW_GET_SCALE";
		case AS_VIEW_SET_DRAWING_MODE: return "AS_VIEW_SET_DRAWING_MODE";
		case AS_VIEW_GET_DRAWING_MODE: return "AS_VIEW_GET_DRAWING_MODE";
		case AS_VIEW_SET_BLENDING_MODE: return "AS_VIEW_SET_BLENDING_MODE";
		case AS_VIEW_GET_BLENDING_MODE: return "AS_VIEW_GET_BLENDING_MODE";
		case AS_VIEW_SET_PEN_LOC: return "AS_VIEW_SET_PEN_LOC";
		case AS_VIEW_GET_PEN_LOC: return "AS_VIEW_GET_PEN_LOC";
		case AS_VIEW_SET_PEN_SIZE: return "AS_VIEW_SET_PEN_SIZE";
		case AS_VIEW_GET_PEN_SIZE: return "AS_VIEW_GET_PEN_SIZE";
		case AS_VIEW_SET_HIGH_COLOR: return "AS_VIEW_SET_HIGH_COLOR";
		case AS_VIEW_SET_HIGH_UI_COLOR: return "AS_VIEW_SET_HIGH_UI_COLOR";
		case AS_VIEW_SET_LOW_COLOR: return "AS_VIEW_SET_LOW_COLOR";
		case AS_VIEW_SET_LOW_UI_COLOR: return "AS_VIEW_SET_LOW_UI_COLOR";
		case AS_VIEW_SET_VIEW_COLOR: return "AS_VIEW_SET_VIEW_COLOR";
		case AS_VIEW_SET_VIEW_UI_COLOR: return "AS_VIEW_SET_VIEW_UI_COLOR";
		case AS_VIEW_GET_HIGH_COLOR: return "AS_VIEW_GET_HIGH_COLOR";
		case AS_VIEW_GET_HIGH_UI_COLOR: return "AS_VIEW_GET_HIGH_UI_COLOR";
		case AS_VIEW_GET_LOW_COLOR: return "AS_VIEW_GET_LOW_COLOR";
		case AS_VIEW_GET_LOW_UI_COLOR: return "AS_VIEW_GET_LOW_UI_COLOR";
		case AS_VIEW_GET_VIEW_COLOR: return "AS_VIEW_GET_VIEW_COLOR";
		case AS_VIEW_GET_VIEW_UI_COLOR: return "AS_VIEW_GET_VIEW_UI_COLOR";
		case AS_VIEW_PRINT_ALIASING: return "AS_VIEW_PRINT_ALIASING";
		case AS_VIEW_CLIP_TO_PICTURE: return "AS_VIEW_CLIP_TO_PICTURE";
		case AS_VIEW_GET_CLIP_REGION: return "AS_VIEW_GET_CLIP_REGION";
		case AS_VIEW_DRAW_BITMAP: return "AS_VIEW_DRAW_BITMAP";
		case AS_VIEW_SET_EVENT_MASK: return "AS_VIEW_SET_EVENT_MASK";
		case AS_VIEW_SET_MOUSE_EVENT_MASK: return "AS_VIEW_SET_MOUSE_EVENT_MASK";
		case AS_VIEW_SET_CLIP_REGION: return "AS_VIEW_SET_CLIP_REGION";
		case AS_VIEW_BEGIN_PICTURE: return "AS_VIEW_BEGIN_PICTURE";
		case AS_VIEW_APPEND_TO_PICTURE: return "AS_VIEW_APPEND_TO_PICTURE";
		case AS_VIEW_END_PICTURE: return "AS_VIEW_END_PICTURE";
		case AS_VIEW_COPY_BITS: return "AS_VIEW_COPY_BITS";
		case AS_VIEW_DRAW_PICTURE: return "AS_VIEW_DRAW_PICTURE";
		case AS_VIEW_INVALIDATE_RECT: return "AS_VIEW_INVALIDATE_RECT";
		case AS_VIEW_DELAYED_INVALIDATE_RECT: return "AS_VIEW_DELAYED_INVALIDATE_RECT";
		case AS_VIEW_INVALIDATE_REGION: return "AS_VIEW_INVALIDATE_REGION";
		case AS_VIEW_INVERT_RECT: return "AS_VIEW_INVERT_RECT";
		case AS_VIEW_MOVE_TO: return "AS_VIEW_MOVE_TO";
		case AS_VIEW_RESIZE_TO: return "AS_VIEW_RESIZE_TO";
		case AS_VIEW_SET_STATE: return "AS_VIEW_SET_STATE";
		case AS_VIEW_SET_FONT_STATE: return "AS_VIEW_SET_FONT_STATE";
		case AS_VIEW_GET_STATE: return "AS_VIEW_GET_STATE";
		case AS_VIEW_SET_VIEW_BITMAP: return "AS_VIEW_SET_VIEW_BITMAP";
		case AS_VIEW_SET_PATTERN: return "AS_VIEW_SET_PATTERN";
		case AS_SET_CURRENT_VIEW: return "AS_SET_CURRENT_VIEW";
		case AS_VIEW_BEGIN_LAYER: return "AS_VIEW_BEGIN_LAYER";
		case AS_VIEW_END_LAYER: return "AS_VIEW_END_LAYER";
		case AS_DIRECT_WINDOW_GET_SYNC_DATA: return "AS_DIRECT_WINDOW_GET_SYNC_DATA";
		case AS_DIRECT_WINDOW_SET_FULLSCREEN: return "AS_DIRECT_WINDOW_SET_FULLSCREEN";
		case AS_DIRECT_SCREEN_LOCK: return "AS_DIRECT_SCREEN_LOCK";
		case AS_TALK_TO_DESKTOP_LISTENER: return "AS_TALK_TO_DESKTOP_LISTENER";
		case AS_DUMP_ALLOCATOR: return "AS_DUMP_ALLOCATOR";
		case AS_DUMP_BITMAPS: return "AS_DUMP_BITMAPS";
		case AS_VIEW_SET_TRANSFORM: return "AS_VIEW_SET_TRANSFORM";
		case AS_VIEW_GET_TRANSFORM: return "AS_VIEW_GET_TRANSFORM";
		case AS_VIEW_GET_PARENT_COMPOSITE: return "AS_VIEW_GET_PARENT_COMPOSITE";
		case AS_VIEW_AFFINE_TRANSLATE: return "AS_VIEW_AFFINE_TRANSLATE";
		case AS_VIEW_AFFINE_SCALE: return "AS_VIEW_AFFINE_SCALE";
		case AS_VIEW_AFFINE_ROTATE: return "AS_VIEW_AFFINE_ROTATE";
		case AS_VIEW_SET_FILL_RULE: return "AS_VIEW_SET_FILL_RULE";
		case AS_VIEW_GET_FILL_RULE: return "AS_VIEW_GET_FILL_RULE";
		case AS_VIEW_CLIP_TO_RECT: return "AS_VIEW_CLIP_TO_RECT";
		case AS_VIEW_CLIP_TO_SHAPE: return "AS_VIEW_CLIP_TO_SHAPE";
		case B_QUIT_REQUESTED: return "B_QUIT_REQUESTED";
		default: return "?";
	}
}


}	// namespace BPrivate
