posix_unistd = static_library('posix_unistd',
	'_exit.c',
	'access.c',
	'alarm.c',
	'brk.c',
	'chown.c',
	'chroot.cpp',
	'close.c',
	'conf.cpp',
	'directory.c',
	'dup.c',
	'exec.cpp',
	'fork.c',
	'getlogin.cpp',
	'getpagesize.c',
	'hostname.cpp',
	'ioctl.c',
	'link.c',
	'lockf.cpp',
	'lseek.c',
	'mount.c',
	'nice.c',
	'pause.c',
	'pipe.c',
	'process.c',
	'read.c',
	'sleep.c',
	'sync.c',
	'system.cpp',
	'terminal.c',
	'truncate.c',
	'ttyname.c',
	'ualarm.c',
	'usergroup.cpp',
	'usleep.c',
	'write.c',
	include_directories: [
	],
)
