libposix_locale = static_library('posix_locale',
	'LocaleBackend.cpp',
	'LocaleData.cpp',
	'LocaleDataBridge.cpp',
	'LocaleInternal.cpp',
	'ThreadLocale.cpp',
	'ctype.cpp',
	'ctype_l.cpp',
	'locale_t.cpp',
	'localeconv.cpp',
	'nl_langinfo.cpp',
	'setlocale.cpp',
	'wctype.cpp',
	'wctype_l.cpp',
	include_directories: [
	],
)
