libposix_pthread = static_library('posix_pthread',
	'pthread.cpp',
	'pthread_atfork.c',
	'pthread_attr.c',
	'pthread_barrier.cpp',
	'pthread_cancel.cpp',
	'pthread_cleanup.cpp',
	'pthread_cond.cpp',
	'pthread_condattr.c',
	'pthread_key.cpp',
	'pthread_mutex.cpp',
	'pthread_mutexattr.c',
	'pthread_once.cpp',
	'pthread_rwlock.cpp',
	'pthread_spinlock.cpp',
	include_directories: [
	],
)
