subdir('os')
subdir('posix')

libroot = shared_library('root',
	'libroot_init.c',
	include_directories: [
		hdr_private,
		hdr_private_libroot,
		hdr_private_runtimeloader,
		hdr_private_system,
	],
	link_whole: [
		libos_main,
		libos_arch_x86_64,
#		libposix_arch_x86_64,
#		libposix_crypt,
#		libposix_locale,
		libposix_main,
#		libposix_pthread,
#		libposix_signal,
#		libposix_stdio,
		libposix_musl,
#		libposix_gnu_arch_x86_64,
#		libposix_gnu_ctype,
#		libposix_gnu_ext,
#		libposix_gnu_iconv,
#		libposix_gnu_libio,
#		libposix_gnu_locale,
#		libposix_gnu_math,
#		libposix_gnu_misc,
#		libposix_gnu_regex,
#		libposix_gnu_stdio,
#		libposix_gnu_stdlib,
#		libposix_gnu_wcsmbs,
#		libposix_stdlib,
#		libposix_string,
#		libposix_string_arch_x86_64,
#		libposix_sys,
#		libposix_time,
#		libposix_unistd,
#		libposix_wchar,
#		libposix_malloc,
	],
	link_args: ['-Wl,--version-script,@0@/@1@'.format(meson.current_source_dir(), 'libroot_versions')],
)
