libposix_time = static_library('posix_time',
	'clock.cpp',
	'clock_support.cpp',
	'ctime.c',
	'localtime.cpp',
	'nanosleep.c',
	'stime.c',
	'time.c',
	'timer_support.cpp',
	'timespec_get.cpp',
	cpp_args: [
		'NOID',
		'PCTS=1',
		'STD_INSPIRED',
		'TM_GMTOFF=tm_gmtoff',
		'TM_ZONE=tm_zone',
		'USG_COMPAT',
	],
	include_directories: [
	],
)
