libposix_gnu_math = static_library('posix_gnu_math',
	'cabs.c',
	'cabsf.c',
	'cabsl.c',
	'carg.c',
	'cargf.c',
	'cargl.c',
	'cimag.c',
	'cimagf.c',
	'cimagl.c',
	'conj.c',
	'conjf.c',
	'conjl.c',
	'creal.c',
	'crealf.c',
	'creall.c',
	'k_casinh.c',
	'k_casinhf.c',
	'k_casinhl.c',
	cpp_args: [
		'USE_IN_LIBIO',
		'_GNU_SOURCE',
	],
	include_directories: [
	],
)
